# Generated by Django 4.1 on 2024-05-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0002_patient_patientouthospital_patientinhospital"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(max_length=18),
        ),
    ]
